version: '3.6'
services:
  app:
    image: eclipse-temurin:17
    privileged: true # 最強権限らしいのでほかの方法が知りたい
    ports:
      - 80:8080
    tty: true
    working_dir: /srv
    networks:
      - db-network
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine
    environment:
      - LANG=ja_JP.utf8
      - POSTGRES_DB=line_secretary
      - POSTGRES_PASSWORD=root@pass@1995
    ports:
      - "5432:5432"
    networks:
      db-network:
networks:
  db-network:
    driver: bridge
volumes:
  db-store: