version: '3.6'
services:
  app:
    image: eclipse-temurin:17
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./server:/srv:cached
    working_dir: /srv
    networks:
      - db-network
    depends_on:
      - db
  db:
    container_name: myDB
    build: ./infra/postgres
    volumes:
      - db-store:/var/lib/postgres
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=line_secretary
      - POSTGRES_PASSWORD=root@pass@1995
    ports:
      - "5432:5432"
    networks:
    - db-network
networks:
  db-network:
volumes:
  db-store: