version: '3.6'
services:
  app:
    image: eclipse-temurin:17
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./server:/srv:cached
    working_dir: /srv
    depends_on:
      - mysql
  mysql:
    build: ./infra/mysql
    environment:
      - MYSQL_DATABASE=line_secretary
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root@pass@3559
      - TZ=Uapan
    volumes:
      - db-store:var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-store: