version: '3.6'
services:
  app:
    volumes:
      # amazonec2でAMI=ami-00bc9b7f0e98dc134 (ubuntu)で実行する場合
      - /home/ubuntu/line-secretary/server:/srv:cached
  db:
    volumes:
      - db-store:/var/lib/postgres
      # amazonec2でAMI=ami-00bc9b7f0e98dc134 (ubuntu)で実行する場合
      - /home/ubuntu/line-secretary/initdb.d:/docker-entrypoint-initdb.d