spring:
  profiles:
    include:
      - sec
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/line_secretary?currentSchema=line_secretary
  jpa:
    database-platform : org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
line.bot:
    handler.path: /callback
chatgpt:
  model: gpt-3.5-turbo
  max-retry: 5
  retry-sleep-ms: 5000
google-calendar:
  file-name:
    credential: google-calendar-credentials.json
    # credential: C:\\Users\\user\\workspace\\docker-spring-java\\server\\src\\main\\resources\\google-calendar-credentials.json