spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/line_secretary?currentSchema=line_secretary
  jpa:
    database-platform : org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update