spring:
  profiles:
    include:
      - sec
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/line_secretary?currentSchema=line_secretary
  jpa:
    database-platform : org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
line.bot:
    handler.path: /callback
google-calendar:
  path:
    credential: ./google-calendar-credentials.json
    # credential: C:\\Users\\user\\workspace\\docker-spring-java\\server\\src\\main\\resources\\google-calendar-credentials.json